import assert from 'node:assert/strict';import{test,beforeEach}from'node:test';import{DatabaseSync}from'node:sqlite';import fs from'node:fs';import{Database}from'./database.bundle.mjs';import{loadDomain,rpcAllowlist}from'./domain.bundle.mjs'
let db,sql
beforeEach(()=>{db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('scripts/native/schema.sql','utf8'));db.exec(fs.readFileSync('scripts/native/bootstrap.sql','utf8'));db.exec("INSERT INTO profiles(user_id,email) VALUES('owner','owner@example.invalid'),('customer','customer@example.invalid'); INSERT INTO user_roles(id,user_id,role) VALUES('root','owner','super_admin');");sql={async sql(q,args=[]){return{rows:db.prepare(q).all(...args)}},async batch(items){db.exec('BEGIN');try{let results=items.map(x=>({rows:db.prepare(x.sql).all(...x.args||[])}));db.exec('COMMIT');return{results}}catch(e){db.exec('ROLLBACK');throw e}}}})
function ctx(userId='owner',master=true,companyId){const identity={userId,master,companyId,role:companyId?'owner':undefined};return{identity,admin:new Database(sql,identity,true,true),scoped:new Database(sql,identity,false,true),request:new Request('https://example.invalid'),env:{},blink:{}}}
test('70 named original functions have explicit allowlist',()=>assert.equal(Object.values(rpcAllowlist).flat().length,70))
test('master creates company for existing owner, stages and subscription persist',async()=>{const c=ctx(),load=loadDomain(c),plan=db.prepare('SELECT id FROM plan LIMIT 1').get();const r=await load('src/lib/master.functions').createCompanyWithOwner({data:{nome:'Teste',ownerEmail:'customer@example.invalid',planId:plan.id}});assert.equal(r.ok,true);assert.equal(db.prepare('SELECT count(*) AS n FROM crm_stage WHERE company_id=?').get(r.companyId).n,4);assert.equal(db.prepare('SELECT user_id FROM company_user WHERE company_id=?').get(r.companyId).user_id,'customer');assert.equal(db.prepare('SELECT plan_id FROM subscription WHERE company_id=?').get(r.companyId).plan_id,plan.id)})
test('non-admin cannot create arbitrary company owner',async()=>{await assert.rejects(()=>loadDomain(ctx('customer',false))('src/lib/master.functions').createCompanyWithOwner({data:{nome:'Teste',ownerEmail:'owner@example.invalid'}}),/Acesso negado/)})
test('self-service creates company and contact through migrated functions',async()=>{const c=ctx('customer',false),r=await loadDomain(c)('src/lib/checkout.functions').createCheckoutCompany({data:{nome:'Meu negócio',plano_slug:'starter'}});assert.ok(r.companyId);const load=loadDomain(ctx('customer',false,r.companyId));await load('src/lib/plan.functions').createContact({data:{numero:'5511999999999',nome:'Contato de teste'}});assert.equal(db.prepare('SELECT nome FROM crm_cards WHERE company_id=?').get(r.companyId).nome,'Contato de teste')})
test('self-service installation is idempotent for same account',async()=>{const run=loadDomain(ctx('customer',false))('src/lib/checkout.functions').createCheckoutCompany;const a=await run({data:{nome:'Um',plano_slug:'starter'}}),b=await run({data:{nome:'Dois',plano_slug:'starter'}});assert.equal(a.companyId,b.companyId)})
test('functions reject unauthenticated caller',async()=>{await assert.rejects(()=>loadDomain(ctx('',false))('src/lib/master.functions').masterKpis(),/Autenticação/)})

test('CSAT creates a token but does not claim delivery without WhatsApp',async()=>{const c=ctx('customer',false),r=await loadDomain(c)('src/lib/checkout.functions').createCheckoutCompany({data:{nome:'CSAT test',plano_slug:'starter'}});const load=loadDomain(ctx('customer',false,r.companyId));const survey=await load('src/lib/csat.functions').sendCsat({data:{numero:'5511999999999'}});assert.match(survey.token,/^[a-f0-9-]{36}$/);assert.equal(survey.sent,false);const publicLoad=loadDomain(ctx('',false));await publicLoad('src/lib/csat.functions').submitCsat({data:{token:survey.token,score:5}});assert.equal(db.prepare('SELECT score FROM csat_response WHERE token=?').get(survey.token).score,5)});
