CREATE TABLE IF NOT EXISTS template_owner(id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE);
INSERT INTO plan(id,slug,nome,descricao,preco_cents,moeda,intervalo,trial_days,limite_mensagens,limite_instancias,limite_usuarios,limite_contatos,features,destaque,ativo,ordem,paddle_product_id,paddle_price_id,stripe_product_id,stripe_price_id,checkout_url,creditos_mensais,creditos_trial,created_at,updated_at) VALUES('plan_starter','starter','Starter','Para começar','9700','BRL','month','3','1000','1','2','500','[]','0','1','1',NULL,NULL,NULL,NULL,NULL,'1000','100','2026-09-16 18:34:49','2026-09-16 18:34:49') ON CONFLICT(id) DO NOTHING;
INSERT INTO plan(id,slug,nome,descricao,preco_cents,moeda,intervalo,trial_days,limite_mensagens,limite_instancias,limite_usuarios,limite_contatos,features,destaque,ativo,ordem,paddle_product_id,paddle_price_id,stripe_product_id,stripe_price_id,checkout_url,creditos_mensais,creditos_trial,created_at,updated_at) VALUES('plan_pro','pro','Pro','Para times que vendem todo dia','19700','BRL','month','3','10000','2','10','5000','[]','1','1','2',NULL,NULL,NULL,NULL,NULL,'10000','1000','2026-09-16 18:34:49','2026-09-16 18:34:49') ON CONFLICT(id) DO NOTHING;
INSERT INTO plan(id,slug,nome,descricao,preco_cents,moeda,intervalo,trial_days,limite_mensagens,limite_instancias,limite_usuarios,limite_contatos,features,destaque,ativo,ordem,paddle_product_id,paddle_price_id,stripe_product_id,stripe_price_id,checkout_url,creditos_mensais,creditos_trial,created_at,updated_at) VALUES('plan_business','business','Business','Para operação em escala','49700','BRL','month','3','50000','5','50','25000','[]','0','1','3',NULL,NULL,NULL,NULL,NULL,'50000','5000','2026-09-16 18:34:49','2026-09-16 18:34:49') ON CONFLICT(id) DO NOTHING;
CREATE TRIGGER IF NOT EXISTS native_company_defaults AFTER INSERT ON company BEGIN
UPDATE company SET primary_color=COALESCE(primary_color,'#25D366'),onboarding_completed=COALESCE(onboarding_completed,0),creditos_saldo=COALESCE((SELECT creditos_trial FROM plan WHERE slug=COALESCE(NEW.selected_plan_slug,'starter')),100) WHERE id=NEW.id;
INSERT INTO crm_stage(id,company_id,nome,ordem,cor,tipo) VALUES(NEW.id||':stage:0',NEW.id,'Conversas',0,'#8AA89A','normal');
INSERT INTO crm_stage(id,company_id,nome,ordem,cor,tipo) VALUES(NEW.id||':stage:1',NEW.id,'Negociando',1,'#FFB020','normal');
INSERT INTO crm_stage(id,company_id,nome,ordem,cor,tipo) VALUES(NEW.id||':stage:2',NEW.id,'Ganho',2,'#22B85F','ganho');
INSERT INTO crm_stage(id,company_id,nome,ordem,cor,tipo) VALUES(NEW.id||':stage:3',NEW.id,'Perda',3,'#FF5A5A','perda');
INSERT INTO agent_config(id,company_id,user_id,nome_agente,nome_empresa,palavra_pausar,palavra_despausar,ai_provider,ai_model) VALUES(NEW.id||':agent',NEW.id,NEW.created_by,'Assistente',NEW.nome,'/pausar','/despausar','gemini','google/gemini-2.5-flash');
END;
UPDATE plan SET features='[]' WHERE features='{}' OR features IS NULL;
